events {}
http {
    log_format json_trap escape=json
    '{"message": "Unauthorized Web Access", '
    '"attacker_ip": "$remote_addr", '
    '"target_node": "$hostname", '
    '"severity": "critical", '
    '"request": "$request", '
    '"status": "$status", '
    '"user_agent": "$http_user_agent"}';

    # Write to a REAL file instead of the Docker stdout symlink
    access_log /tmp/trap.log json_trap;

    server {
        listen 80;
        location / {
            return 200 "<h1>Internal Server Error - Admin Portal Offline</h1>\n";
        }
    }
}
