input {
  tcp {
    port => 5000
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "eidolon-honeypot-%{+YYYY.MM.dd}"
  }
  # This prints the logs to the terminal so we can verify it's working
  stdout { codec => rubydebug } 
}
